services:
  app:
    build: .
    ports:
      - "3000:3001"
    depends_on:
      app-build:
        condition: service_completed_successfully
    working_dir: /app
    volumes:
      - .:/app


  app-build:
    profiles:
      - build
    image: node:23.7.0-bookworm-slim
    working_dir: /app
    volumes:
      - .:/app
    command:
      - "npm"
      - "install"

